### ISSUE TITLE
Does the package in production ready?

### ISSUE THREAD

**Issue by yoka791** [cbuschka/go-spring-password-encoder#1]
Hi,
Does the package in production ready?
Thanks!

**Comment by cbuschka** [comment]
I have written the lib to replace a legacy spring oauth server with a golang one to save some resources. Regarding SHA256 it works fine, match and encode. Regarding the bcrypt encoding, the tests show it to be compatible. But because it is based on the go builtin bcrypt encoding it could be if bcrypt evolves that spring and golang diverge. Then we have to investigate. For the SHA256/StandardPasswordEncoder stuff this lib is in production of a small site.

**Comment by cbuschka** [comment]
Looks like it has been solved :)
